{% set name = "rever" %}
{% set version = "0.4.2" %}
{% set sha256 = "3341e4594ed74fa75c9084931a244a3709b1fde01147150d05c620e1851886ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ergs/rever/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install
  skip: True  # [py2k]

requirements:
  build:
    - python
  run:
    - python
    - xonsh
    - lazyasd
    - github3.py
    - ruamel.yaml

test:
  imports:
    - rever
    - rever.activities
  commands:
    - rever -h

about:
  home: https://regro.github.io/rever-docs/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Releaser of Versions'
  description: |
    Rever is a xonsh-powered, cross-platform software release tool. The goal of rever is
    to provide sofware projects a standard mechanism for dealing with code released.
    Rever aims to make the process of releasing a new version of a code base as easy as
    running a single command.
  doc_url: https://regro.github.io/rever-docs/
  dev_url: https://github.com/ergs/rever

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - CJ-Wright
