{% set name = "rever" %}
{% set version = "0.4.3" %}
{% set sha256 = "a722b98172ce26282efbb72bf15567e1b7c7b5f131ddf352e855e3d1fdf95290" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ergs/rever/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - rever = rever.main:main
  
requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - xonsh
    - lazyasd
    - github3.py
    - ruamel.yaml

test:
  imports:
    - rever
    - rever.activities
  commands:
    - rever -h

about:
  home: https://regro.github.io/rever-docs/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Releaser of Versions'
  description: |
    Rever is a xonsh-powered, cross-platform software release tool. The goal of rever is
    to provide sofware projects a standard mechanism for dealing with code released.
    Rever aims to make the process of releasing a new version of a code base as easy as
    running a single command.
  doc_url: https://regro.github.io/rever-docs/
  dev_url: https://github.com/ergs/rever

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - CJ-Wright
