appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kV9dS1hykWEHlg4y7iGuQLtIGbSW1S/CrJUTtpjfXRfPYE/yU2GttFJK+XK8Wlj3apQGsLpscJQkPpY9TgtTAAfOHhcn8s1wH6duUQFRT3N+UIsgW+0UWc/LbXI5cx2u2B6Cn41uNMnbPJlCgDD9q+1mdpKfR6/sUSaaWm9aTEZ/bHN96ZLWQSPChozfZmhGBaY2BlfwSczdom0G1oqQVzi61Pvd2IItDBO9YS1JG95ZEkQ+trSaTGAGEtJKiMyLcHKGT4aN7ATXtLDMlMuH4D/CNuLOQxtYfqzTDmwEGx+bLmOy8IMryzMIsULC+yBa3rDvAC8DWbhs0CTpM94F/LmcGIvLQBSnZUYBROq6L7dvzuHjKeGYgu8L9mb8DJSLhImjh44132dzYftWLXFn4vR+BhSgSrnnwyixBUCBM01w/aqgqop8Yy0U50wtTMVHPUQhtBdaHFs5RI6cDI8sDUPjKVWisx3sDlo3odciiwuDwh0uhQsG9OPja0ctiyE9WqaG4z/Bi3NvgtyNatjNeHhNtHqoYJFXS3KqNeyIZMpU66klQX3sKNlq6978B7Sr6vDwD82a13/UbQOkrFasIcqbuuWjC6Tj/S3mYGwXxGogY0QgMsX262i9fjSfqoUMq/+F6lQ7vfUby0cfRJOrW3fN59N7WqkW01iWWvaJY7M=}
